name: Archive External Kernel

on:
  workflow_dispatch:

jobs:
  archive-and-release:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    permissions:
      contents: write

    steps:
      # --- FIX 1: CHECK OUT YOUR REPOSITORY ---
      # This step is crucial. It puts the runner in the context of your
      # repository, which is required by the 'gh release create' command.
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git xz-utils

      - name: Clone Android Common Kernel (4.14 Branch)
        run: |
          echo "Starting full clone of the android-4.14-stable branch..."
          git clone --progress --branch=deprecated/android-4.14-stable https://android.googlesource.com/kernel/common/ android-kernel
          
      - name: Fetch All Tags
        run: |
          cd android-kernel
          git fetch --tags
          cd ..

      - name: Check Disk Usage After Clone
        run: du -sh android-kernel

      - name: Compress Kernel Source
        run: |
          echo "Starting compression..."
          tar -I 'xz -7 -T0' -cvf android-kernel-4.14.tar.xz android-kernel

      - name: Check Final Archive Size
        run: ls -lh android-kernel-4.14.tar.xz

      # --- FIX 2: SPLIT THE LARGE ARCHIVE ---
      - name: Split Archive into Chunks
        run: |
          echo "Splitting the 6.3GB archive into smaller parts..."
          # Split into 1.9GB chunks to stay safely under the 2GB limit.
          split -b 1900M android-kernel-4.14.tar.xz "android-kernel-4.14.tar.xz.part-" -a 2 -d

      - name: Create GitHub Release and Upload Chunks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=$(date +'%Y-%m-%d-%H%M')
          
          # --- FIX 2 (Continued): UPDATE RELEASE NOTES WITH INSTRUCTIONS ---
          RELEASE_NOTES="Automated archive of the Android Common Kernel deprecated/android-4.14-stable branch.

          **IMPORTANT:** This archive was split into multiple parts due to GitHub's file size limit. To reassemble the archive, download all \`.part-*\` files into the same directory and run the following command in your terminal:

          \`\`\`bash
          cat android-kernel-4.14.tar.xz.part-* > android-kernel-4.14.tar.xz
          \`\`\`
          "
          
          echo "Creating release with tag: $TAG"
          gh release create "$TAG" \
              --title "Android Kernel 4.14 Archive ($TAG)" \
              --notes "$RELEASE_NOTES"

          echo "Uploading archive parts to the release..."
          # --- FIX 2 (Continued): UPLOAD ALL THE SPLIT FILES ---
          for file in android-kernel-4.14.tar.xz.part-*; do
            echo "Uploading $file..."
            gh release upload "$TAG" "$file"
          done
          
      - name: Clean up runner disk space
        if: always()
        run: |
          echo "Cleaning up large files..."
          rm -rf android-kernel
          rm -f android-kernel-4.14.tar.xz*
